pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building Projeto Aurora...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
